"""Detection benchmark: replays every scenario and reports detection and false-positive figures.

`sentinel bench` prints the report; `--output FILE` writes it and `--check FILE` (used by CI) fails
if the committed file no longer matches what the scenarios produce. The report is deterministic
(no timestamps, no timings), so that a stale committed copy is detectable.
"""

import argparse
import asyncio
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from uuid import UUID

from sentinel_core.detection.engine import DetectionEngine
from sentinel_core.detection.rules import Rule, RuleLoadError, load_rules
from sentinel_core.detection.scenarios import (
    REPLAY_RECEIVED_AT,
    SHARED,
    ScenarioError,
    ScenarioResult,
    discover_scenarios,
    run_scenario,
)
from sentinel_core.detection.store import InMemoryWindowStore
from sentinel_core.normalizers.base import ParseError, RawLog
from sentinel_core.normalizers.registry import NORMALIZERS
from sentinel_core.schema.event import Source

_OK, _KO = "✅", "❌"


@dataclass(frozen=True)
class BenchmarkRun:
    rules: list[Rule]
    results: list[ScenarioResult]

    @property
    def ok(self) -> bool:
        return all(result.passed for result in self.results)


@dataclass(frozen=True)
class Throughput:
    events: int
    seconds: float

    @property
    def events_per_second(self) -> float:
        return self.events / self.seconds


async def run_benchmark(rules: Sequence[Rule], datasets_dir: Path) -> BenchmarkRun:
    scenarios = discover_scenarios(datasets_dir, [rule.id for rule in rules])
    return BenchmarkRun(list(rules), [await run_scenario(s, rules) for s in scenarios])


def _pct(part: int, whole: int) -> str:
    return f"{part}/{whole} ({round(100 * part / whole)}%)" if whole else "0/0"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_report(run: BenchmarkRun) -> str:
    attacks = [r for r in run.results if r.scenario.kind == "attack"]
    benign = [r for r in run.results if r.scenario.kind == "benign"]
    negative = [r for r in run.results if r.scenario.kind == "negative"]
    shared = [r for r in benign if r.scenario.rule_id == SHARED]
    detected = [r for r in attacks if r.alerts.get(r.scenario.rule_id, 0) >= 1]
    noisy = [r for r in benign if r.alerts]
    false_alerts = sum(sum(r.alerts.values()) for r in benign)

    out = [
        "# Detection benchmark",
        "",
        "Generated by `sentinel bench` from `rules/` and `datasets/` — **do not edit by hand**: "
        "CI fails if this file is out of date. Regenerate with "
        "`cd backend && uv run sentinel bench --output ../docs/BENCHMARK.md`.",
        "",
        "## Summary",
        "",
        "| | |",
        "|---|---|",
        f"| Rules | {len(run.rules)} |",
        f"| Attack scenarios | {len(attacks)} |",
        f"| Attack scenarios detected | {_pct(len(detected), len(attacks))} |",
        f"| Scenarios matching their expectations (exact alert counts) | "
        f"{_pct(sum(r.passed for r in run.results), len(run.results))} |",
        f"| Negative scenarios (the rule must stay silent) | {len(negative)} "
        f"({sum(r.passed for r in negative)}/{len(negative)} as expected) |",
        f"| Benign scenarios | {len(benign)} ({len(shared)} shared across all rules) |",
        f"| Benign scenarios with a false alert | {len(noisy)}/{len(benign)} |",
        f"| Benign events replayed | {sum(r.events for r in benign)} |",
        f"| False alerts on benign traffic | {false_alerts} |",
        "",
        "## Per rule",
        "",
        "Benign columns count the rule's own benign scenarios **and** the shared ones: a rule "
        "must stay silent on all of them. A negative scenario is a near miss: the rule must "
        "not fire while the related rules fire exactly as declared (e.g. a sequence whose second "
        "step comes too late).",
        "",
        "| Rule | MITRE | Attacks detected | Negatives silent | Benign clean | False alerts |",
        "|---|---|---|---|---|---|",
    ]
    for rule in sorted(run.rules, key=lambda r: r.id):
        own_attacks = [r for r in attacks if r.scenario.rule_id == rule.id]
        own_detected = [r for r in own_attacks if r.alerts.get(rule.id, 0) >= 1]
        own_negative = [r for r in negative if r.scenario.rule_id == rule.id]
        own_silent = [r for r in own_negative if not r.alerts.get(rule.id, 0)]
        relevant = [r for r in benign if r.scenario.rule_id in (rule.id, SHARED)]
        clean = [r for r in relevant if not r.alerts.get(rule.id, 0)]
        wrong = sum(r.alerts.get(rule.id, 0) for r in relevant)
        out.append(
            f"| {rule.id} | {', '.join(rule.mitre)} | {len(own_detected)}/{len(own_attacks)} "
            f"| {len(own_silent)}/{len(own_negative)} | {len(clean)}/{len(relevant)} | {wrong} |"
        )

    out += [
        "",
        "## Scenarios",
        "",
        "| Rule | Scenario | Kind | Events | Expected | Alerts | Result | Notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in run.results:
        s = r.scenario
        expected = str(s.expect) + "".join(f", {k}={v}" for k, v in sorted(s.also.items()))
        alerts = ", ".join(f"{k}={v}" for k, v in sorted(r.alerts.items())) or "-"
        notes = "; ".join(r.problems) if r.problems else s.description
        out.append(
            f"| {'(all rules)' if s.rule_id == SHARED else s.rule_id} | {s.name} | {s.kind} "
            f"| {r.events} | {expected} | {_cell(alerts)} | {_OK if r.passed else _KO} "
            f"| {_cell(notes)} |"
        )

    out += [
        "",
        "## How to read these numbers",
        "",
        "- The scenarios are **curated by the rule author** (synthetic attacks, a synthetic normal "
        "day): the detection rate is a regression measure of the rules, not an estimate of "
        'real-world detection, and "0 false alerts" only covers the benign traffic that exists in '
        "`datasets/`.",
        "- Every scenario is replayed like production does (normalizer, then the engine with "
        "**all** rules loaded). Benign scenarios must raise no alert from any rule; an attack "
        "must raise exactly the declared number of alerts, from the owning rule and from the "
        "rules it declares with `# also`.",
        "- Detection *delay* is a property of the running system, not of these files: see the lab "
        "measurement in [`lab/README.md`](../lab/README.md). Engine throughput: `sentinel bench "
        "--throughput` (varies per machine, therefore not part of this file).",
        "",
    ]
    return "\n".join(out)


async def measure_throughput(
    rules: Sequence[Rule], datasets_dir: Path, repeat: int = 20
) -> Throughput:
    """Normalize + detect the benign scenarios `repeat` times (fresh engine each time), in memory.

    A single core, no network, no database: a ceiling for the detection logic, not an
    end-to-end figure.
    """
    scenarios = [
        s
        for s in discover_scenarios(datasets_dir, [rule.id for rule in rules])
        if s.kind == "benign"
    ]
    events = 0
    started = time.perf_counter()
    for _ in range(repeat):
        engine = DetectionEngine(rules, InMemoryWindowStore())
        for scenario in scenarios:
            normalizer = NORMALIZERS[Source(scenario.source)]
            for number, line in enumerate(scenario.lines):
                raw = RawLog(
                    agent_id=UUID(int=1),
                    source=Source(scenario.source),
                    origin=f"{scenario.name}:{number}",
                    line=line,
                    received_at=REPLAY_RECEIVED_AT,
                )
                try:
                    event = normalizer.normalize(raw)
                except ParseError:
                    continue
                if event is not None:
                    events += 1
                    await engine.evaluate(event)
    return Throughput(events, time.perf_counter() - started)


def _default_dir(name: str) -> Path:
    """`rules` / `datasets` from the repository root or from `backend/`."""
    return Path(name) if Path(name).is_dir() else Path("..") / name


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--rules", type=Path, default=None, help="rules directory (default: rules)")
    parser.add_argument("--datasets", type=Path, default=None, help="datasets directory")
    parser.add_argument("--output", type=Path, help="write the report to this file")
    parser.add_argument("--check", type=Path, help="fail if this file differs from the report")
    parser.add_argument("--throughput", action="store_true", help="also measure engine throughput")


def run_command(args: argparse.Namespace) -> int:
    rules_dir = args.rules or _default_dir("rules")
    datasets_dir = args.datasets or _default_dir("datasets")
    try:
        rules = load_rules(rules_dir)
        run = asyncio.run(run_benchmark(rules, datasets_dir))
    except (RuleLoadError, ScenarioError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    report = render_report(run)

    if args.check:
        try:
            committed = args.check.read_text()
        except OSError as exc:
            print(f"error: cannot read {args.check}: {exc.strerror}", file=sys.stderr)
            return 1
        if committed != report:
            print(
                f"error: {args.check} is out of date: regenerate it with "
                f"`sentinel bench --output {args.check}`",
                file=sys.stderr,
            )
            return 1
    elif args.output:
        args.output.write_text(report)
        print(f"wrote {args.output}")
    else:
        print(report)

    if args.throughput:
        speed = asyncio.run(measure_throughput(rules, datasets_dir))
        print(
            f"engine throughput: {speed.events} events in {speed.seconds:.2f} s = "
            f"{speed.events_per_second:,.0f} events/s (normalize + detect, in memory, one core; "
            "not end-to-end)"
        )
    if not run.ok:
        print("benchmark FAILED: some scenarios do not match their expectations", file=sys.stderr)
    return 0 if run.ok else 1
